name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --scope ayer-ribeiros-projects
        env:
          VERCEL_ORG_ID: team_jilvMmsDkvnA930bGphPnMvF
          VERCEL_PROJECT_ID: prj_8BaTHuHgBIAs3HpkK8S8lX1Zzh9L
